In [ ]:
import pandas as pd
import numpy as np

In [ ]:
pop1 = pd.read_csv('qgis/최종 1 고령인구.csv',encoding='cp949')
pop3 = pd.read_csv('qgis/최종 3 고령인구.csv',encoding='cp949')

C:\Users\JIHYE\AppData\Local\Temp\ipykernel_11448\1173065782.py:1: DtypeWarning: Columns (3,4,8,9,10,11,12,13,14,15,16,17,18,19,20,25,26,28,31,32,33,40,41,42,44,45,52) have mixed types. Specify dtype option on import or set low_memory=False.
  pop1 = pd.read_csv('qgis/최종 1 고령인구.csv',encoding='cp949')
C:\Users\JIHYE\AppData\Local\Temp\ipykernel_11448\1173065782.py:2: DtypeWarning: Columns (3,4,5,8,9,10,11,12,13,14,15,16,17,18,19,20,24,25,26,28,31,32,33,40,41,42,44,45,46,47,48,49,50,51,52) have mixed types. Specify dtype option on import or set low_memory=False.
  pop3 = pd.read_csv('qgis/최종 3 고령인구.csv',encoding='cp949')

In [ ]:
pop1.keys()

Index(['fid', 'field_1', 'Unnamed: 0', '약국명_y', '주소_y', '전화번호', '좌표정보(X)',
       '좌표정보(Y)', '월요일 운영', '화요일 운영', '수요일 운영', '목요일 운영', '금요일 운영', '토요일 운영',
       '일요일 운영', '공휴일 운영', '시도명', '시군구명', '읍면명', '회관명', '소재지', 'Latitude',
       'Longitude', '규모(제곱미터)', '데이터기준일자', '마을회관명', '소재지도로명주소', '회원수', '대표자',
       '대지면적', '건축면적', '경로당명', '주소', '연락처', '연번', '명칭', '관장', '시설소재지', '시설설치일',
       '위탁 또는 운영단체', '보건소명', '일반전화', '팩스', '우편번호', '도로명주소', '위치', '시군명', '기관장',
       '기관명', '소재지 (도로명 주소)', '진료과목', '진료시간', '비고', 'layer', 'path', 'ringId',
       'distance', 'fid_2', 'gid', 'lbl', 'val', 'layer_2', 'path_2'],
      dtype='object')

In [ ]:
pop3.keys()

Index(['fid', 'field_1', 'Unnamed: 0', '약국명_y', '주소_y', '전화번호', '좌표정보(X)',
       '좌표정보(Y)', '월요일 운영', '화요일 운영', '수요일 운영', '목요일 운영', '금요일 운영', '토요일 운영',
       '일요일 운영', '공휴일 운영', '시도명', '시군구명', '읍면명', '회관명', '소재지', 'Latitude',
       'Longitude', '규모(제곱미터)', '데이터기준일자', '마을회관명', '소재지도로명주소', '회원수', '대표자',
       '대지면적', '건축면적', '경로당명', '주소', '연락처', '연번', '명칭', '관장', '시설소재지', '시설설치일',
       '위탁 또는 운영단체', '보건소명', '일반전화', '팩스', '우편번호', '도로명주소', '위치', '시군명', '기관장',
       '기관명', '소재지 (도로명 주소)', '진료과목', '진료시간', '비고', 'layer', 'path', 'ringId',
       'distance', 'fid_2', 'gid', 'lbl', 'val', 'layer_2', 'path_2'],
      dtype='object')

In [ ]:
layer = list(pop1['layer'].unique())
layer

['1차 설치지역(휴안바깥약국)',
 '경로담_담양',
 '전라남도보건지소현황_20210801 - 전라남도보건지소현황_20210801',
 '전라남도보건진료소현황_20210801 - 전라남도보건진료소현황_20210801',
 '경로당_함평',
 '경로당_신안',
 '전라남도_보건소현황_20210801 - 전라남도_보건소현황_20210801']

In [ ]:
pop1['layer_2'].unique()

array(['담양250', '신안250', '함평250'], dtype=object)

In [ ]:
layer[0]

'1차 설치지역(휴안바깥약국)'

In [ ]:
pop1_drugstore = pop1[pop1['layer']==layer[0]]
pop1_welfare_DamYang = pop1[pop1['layer']==layer[1]]
pop1_healthB = pop1[pop1['layer']==layer[2]]
pop1_healthC = pop1[pop1['layer']==layer[3]]
pop1_welfare_HamPyeong = pop1[pop1['layer']==layer[4]]
pop1_welfare_ShinAhn = pop1[pop1['layer']==layer[5]]
pop1_healthA = pop1[pop1['layer']==layer[6]]

In [ ]:
pop1_drugstore = pop1_drugstore[['약국명_y','layer_2','좌표정보(X)','좌표정보(Y)','gid','val']]
pop1_drugstore.rename(columns={'약국명_y':'name',
                               '좌표정보(X)':'Longitude',
                               '좌표정보(Y)':'Latitude'}
                      ,inplace=True)
pop1_drugstore

     name layer_2   Longitude   Latitude         gid   val
0    고서약국   담양250  126.973754  35.223375  다라51aa91ba   6.0
1    고서약국   담양250  126.973754  35.223375  다라51aa91bb  22.0
2    고서약국   담양250  126.973754  35.223375  다라51aa92aa  12.0
3    고서약국   담양250  126.973754  35.223375  다라51aa92ab   NaN
4    고서약국   담양250  126.973754  35.223375  다라51aa92ba   NaN
..    ...     ...         ...        ...         ...   ...
772  한재약국   담양250  126.887137  35.276294  다라45aa98aa  10.0
773  한재약국   담양250  126.887137  35.276294  다라45aa98ab   0.0
774  한재약국   담양250  126.887137  35.276294  다라45aa98ba   NaN
775  한재약국   담양250  126.887137  35.276294  다라45ab97bb  19.0
776  한재약국   담양250  126.887137  35.276294  다라45ab98aa   9.0

[777 rows x 6 columns]

In [ ]:
pop1_welfare_DamYang = pop1_welfare_DamYang[['회관명','layer_2','Longitude','Latitude','gid','val']]
pop1_welfare_DamYang.rename(columns={'회관명':'name'},inplace=True)
pop1_welfare_DamYang

           name layer_2   Longitude   Latitude         gid  val
777    연화촌 마을회관   담양250  127.017723  35.334122  다마55aa04aa  0.0
778    연화촌 마을회관   담양250  127.017723  35.334122  다마55aa04ab  NaN
779    연화촌 마을회관   담양250  127.017723  35.334122  다마55aa04ba  7.0
780    연화촌 마을회관   담양250  127.017723  35.334122  다마55aa04bb  0.0
781    연화촌 마을회관   담양250  127.017723  35.334122  다마55ab03ba  NaN
...         ...     ...         ...        ...         ...  ...
15354   계곡 마을회관   담양250  126.902177  35.286186  다마45aa00aa  NaN
15355   계곡 마을회관   담양250  126.902177  35.286186  다마45ab00aa  NaN
15356   계곡 마을회관   담양250  126.902177  35.286186  다마45ba00aa  NaN
15357   계곡 마을회관   담양250  126.902177  35.286186  다마45bb00aa  NaN
15358   계곡 마을회관   담양250  126.902177  35.286186  다마46aa00aa  NaN

[14582 rows x 6 columns]

In [ ]:
pop1_welfare_DamYang.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 14582 entries, 777 to 15358
Data columns (total 6 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   name       14582 non-null  object
 1   layer_2    14582 non-null  object
 2   Longitude  14582 non-null  float64
 3   Latitude   14582 non-null  float64
 4   gid        14582 non-null  object
 5   val        5549 non-null   float64
dtypes: float64(3), object(3)
memory usage: 797.5+ KB

In [ ]:
pop1_welfare_HamPyeong = pop1_welfare_HamPyeong[['경로당명','layer_2','Longitude','Latitude','gid','val']]
pop1_welfare_HamPyeong.rename(columns={'경로당명':'name'},inplace=True)
pop1_welfare_HamPyeong

      name layer_2   Longitude   Latitude         gid   val
16765   수호   함평250  126.513613  35.054433  다라09aa73aa   NaN
16766   수호   함평250  126.513613  35.054433  다라09aa73ab   NaN
16767   수호   함평250  126.513613  35.054433  다라09aa73ba   NaN
16768   수호   함평250  126.513613  35.054433  다라09aa73bb   NaN
16769   수호   함평250  126.513613  35.054433  다라09aa74aa   NaN
...    ...     ...         ...        ...         ...   ...
37142   덕산   함평250  126.601443  35.223830  다라19aa92aa  13.0
37143   덕산   함평250  126.601443  35.223830  다라19aa92ab   0.0
37144   덕산   함평250  126.601443  35.223830  다라19aa92ba   NaN
37145   덕산   함평250  126.601443  35.223830  다라19aa92bb   7.0
37146   덕산   함평250  126.601443  35.223830  다라19aa93aa   NaN

[20382 rows x 6 columns]

In [ ]:
pop1_welfare_ShinAhn = pop1_welfare_ShinAhn[['마을회관명','layer_2','Longitude','Latitude','gid','val']]
pop1_welfare_ShinAhn.rename(columns={'마을회관명':'name'},inplace=True)
pop1_welfare_ShinAhn

      name layer_2   Longitude   Latitude         gid   val
38507  원심동   신안250  126.191315  35.098625  나라79ba78ba  16.0
38508  원심동   신안250  126.191315  35.098625  나라79ba78bb   NaN
38509  원심동   신안250  126.191315  35.098625  나라79ba79aa   NaN
38510  원심동   신안250  126.191315  35.098625  나라79bb78ab   NaN
38511  원심동   신안250  126.191315  35.098625  나라79bb78ba   NaN
...    ...     ...         ...        ...         ...   ...
42217   마산   신안250  126.249209  34.952552  나라86ab63ba   NaN
42218   마산   신안250  126.249209  34.952552  나라86ba63aa   NaN
42219   마산   신안250  126.249209  34.952552  나라86ba63ab   NaN
42220   마산   신안250  126.249209  34.952552  나라86bb62ba   NaN
42221   마산   신안250  126.249209  34.952552  나라86bb62bb   NaN

[3715 rows x 6 columns]

In [ ]:
pop1_healthA = pop1_healthA[['보건소명','layer_2','Longitude','Latitude','gid','val']]
pop1_healthB = pop1_healthB[['기관명','layer_2','Longitude','Latitude','gid','val']]
pop1_healthC = pop1_healthC[['기관명','layer_2','Longitude','Latitude','gid','val']]
pop1_healthA.rename(columns={'보건소명':'name'},inplace=True)
pop1_healthB.rename(columns={'기관명':'name'},inplace=True)
pop1_healthC.rename(columns={'기관명':'name'},inplace=True)

In [ ]:
pop1 = pd.concat([pop1_drugstore, pop1_welfare_DamYang,
                  pop1_welfare_ShinAhn,pop1_welfare_HamPyeong,
                  pop1_healthA,pop1_healthB,pop1_healthC],
                 axis=0,
                 ignore_index = True)

In [ ]:
pop1.drop('index',axis=1,inplace=True)
pop1.keys()

Index(['name', 'layer_2', 'Longitude', 'Latitude', 'gid', 'val'], dtype='object')

In [ ]:
pop1['index'] = pop1['name'] + str(pop1['Longitude'])

In [ ]:
pop1

,name,layer_2,Longitude,Latitude,gid,val,index
0,고서약국,담양250,126.973754,35.223375,다라51aa91ba,6.0,고서약국0 126.973754\n1 126.973754\n...
1,고서약국,담양250,126.973754,35.223375,다라51aa91bb,22.0,고서약국0 126.973754\n1 126.973754\n...
2,고서약국,담양250,126.973754,35.223375,다라51aa92aa,12.0,고서약국0 126.973754\n1 126.973754\n...
3,고서약국,담양250,126.973754,35.223375,다라51aa92ab,NaN,고서약국0 126.973754\n1 126.973754\n...
4,고서약국,담양250,126.973754,35.223375,다라51aa92ba,NaN,고서약국0 126.973754\n1 126.973754\n...
...,...,...,...,...,...,...,...
43866,추포도보건진료소,신안250,126.066108,34.812837,나라69ba47aa,NaN,추포도보건진료소0 126.973754\n1 126.9737...
43867,추포도보건진료소,신안250,126.066108,34.812837,나라69ba47ab,NaN,추포도보건진료소0 126.973754\n1 126.9737...
43868,추포도보건진료소,신안250,126.066108,34.812837,나라69ba47ba,NaN,추포도보건진료소0 126.973754\n1 126.9737...
43869,추포도보건진료소,신안250,126.066108,34.812837,나라69ba47bb,NaN,추포도보건진료소0 126.973754\n1 126.9737...
43870,추포도보건진료소,신안250,126.066108,34.812837,나라69bb47bb,NaN,추포도보건진료소0 126.973754\n1 126.9737...

In [ ]:
pop1['index'] = str(pop1['Latitude']) + str(pop1['Longitude'])

In [ ]:
pop1['name'].nunique()

638

In [ ]:
pop1_ = pop1.groupby('name').sum('val')

In [ ]:
pop1_

             Longitude     Latitude    val
name
가거도보건지소    6381.482110  1736.673328   73.0
가곡 마을회관    8505.966213  2367.794278  238.0
가동         8347.530464  2315.235556  138.0
가라실 마을회관   8764.760425  2438.693386  269.0
가란         5180.993274  1429.839859   30.0
...                ...          ...    ...
회춘동        8604.715838  2380.816401  375.0
효지         8206.425000  2278.286933  144.0
후산 마을회관    8507.201479  2359.976262  356.0
흥용         8474.825605  2350.223769  161.0
흥용동       13668.762412  3779.747540  182.0

[638 rows x 3 columns]

In [ ]:
pop1_.to_csv('qgis/고령인구3km.csv',encoding='cp949')